# Generated by Django 5.2.5 on 2026-07-08 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_fix_stripe_field_placement'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedWebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=255, unique=True)),
                ('event_type', models.CharField(max_length=100)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
