# Generated by Django 6.0.4 on 2026-05-22 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0002_organization_subscription_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=100)),
                ('user_id', models.IntegerField()),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
            ],
            options={
                'indexes': [models.Index(fields=['organization', 'event_type'], name='analytics_a_organiz_cf4723_idx'), models.Index(fields=['created_at'], name='analytics_a_created_546677_idx')],
            },
        ),
    ]
