# Generated by Django 6.0.4 on 2026-05-22 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='subscription_status',
            field=models.CharField(default='active', max_length=20),
        ),
    ]
