# Generated by Django 5.2.5 on 2026-07-07 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_alter_invitation_invited_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='trial_ends_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
