# Generated by Django 5.2.5 on 2026-07-09 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_organization_trial_ends_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='plan',
            field=models.CharField(default='free', max_length=20),
        ),
    ]
